default_platform(:ios)

platform :ios do
  desc "Build for testing"
  lane :build_for_testing do
    scan(
      project: "BluetoothTicTacToe.xcodeproj",
      scheme: "BluetoothTicTacToe", 
      device: "iPhone 15",
      build_for_testing: true,
      code_coverage: true
    )
  end

  desc "Run tests"
  lane :test do
    scan(
      project: "BluetoothTicTacToe.xcodeproj",
      scheme: "BluetoothTicTacToe",
      device: "iPhone 15",
      code_coverage: true
    )
  end

  desc "Build app for simulator"
  lane :build_simulator do
    gym(
      project: "BluetoothTicTacToe.xcodeproj",
      scheme: "BluetoothTicTacToe",
      configuration: "Debug",
      destination: "platform=iOS Simulator,name=iPhone 15,OS=17.0",
      skip_package_ipa: true,
      skip_codesigning: true
    )
  end

  desc "Build and sign app for device"
  lane :build_device do
    match(type: "development")
    gym(
      project: "BluetoothTicTacToe.xcodeproj", 
      scheme: "BluetoothTicTacToe",
      configuration: "Release",
      export_method: "development"
    )
  end

  desc "Deploy to TestFlight"
  lane :beta do
    match(type: "appstore")
    gym(
      project: "BluetoothTicTacToe.xcodeproj",
      scheme: "BluetoothTicTacToe", 
      configuration: "Release",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end