name: iOS Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: List Xcode installations
      run: ls /Applications/ | grep Xcode
    
    - name: Check project file
      run: ls -la BluetoothTicTacToe.xcodeproj/
    
    - name: Validate project
      run: xcodebuild -project BluetoothTicTacToe.xcodeproj -list
    
    - name: Simple build test
      run: |
        xcodebuild -version
        xcodebuild -project BluetoothTicTacToe.xcodeproj \
          -scheme BluetoothTicTacToe \
          -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15' \
          clean build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO