name: iOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    
    - name: Install CocoaPods
      run: |
        if [ -f "Podfile" ]; then
          pod install --repo-update
        fi
    
    - name: Build Project
      run: |
        xcodebuild clean build \
          -project BluetoothTicTacToe.xcodeproj \
          -scheme BluetoothTicTacToe \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE="" \
          | xcpretty
    
    - name: Run Tests
      run: |
        xcodebuild test \
          -project BluetoothTicTacToe.xcodeproj \
          -scheme BluetoothTicTacToe \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty || true
    
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: ios-build-artifacts
        path: |
          build/
          *.ipa
        retention-days: 30

  release-build:
    name: Release Build
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install Apple Certificate and Provisioning Profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # 証明書とプロビジョニングプロファイルをキーチェーンに追加
        if [[ -n "$BUILD_CERTIFICATE_BASE64" ]]; then
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
        fi
    
    - name: Build and Archive
      run: |
        if [[ -n "$BUILD_CERTIFICATE_BASE64" ]]; then
          # 署名付きビルド
          xcodebuild archive \
            -project BluetoothTicTacToe.xcodeproj \
            -scheme BluetoothTicTacToe \
            -destination 'generic/platform=iOS' \
            -archivePath build/BluetoothTicTacToe.xcarchive \
            -configuration Release
          
          xcodebuild -exportArchive \
            -archivePath build/BluetoothTicTacToe.xcarchive \
            -exportPath build/ \
            -exportOptionsPlist ExportOptions.plist
        else
          # 署名なしビルド（シミュレーター用）
          xcodebuild archive \
            -project BluetoothTicTacToe.xcodeproj \
            -scheme BluetoothTicTacToe \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            -archivePath build/BluetoothTicTacToe.xcarchive \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO
        fi
    
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-release-build
        path: |
          build/*.ipa
          build/*.xcarchive
        retention-days: 90